# -*- coding: utf-8 -*-
"""memory_inspection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0gqmJXLTMv5mrQAWVde4SnI96ZU8D59
"""

# memory_inspection.py

a = 10
b = 10

print("Before changing:")
print("a =", a)
print("b =", b)

print("Memory address of a:", id(a))
print("Memory address of b:", id(b))

# Changing one variable
b = 20

print("\nAfter changing b:")
print("a =", a)
print("b =", b)

print("Memory address of a:", id(a))
print("Memory address of b:", id(b))