# -*- coding: utf-8 -*-
"""student_formatter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0gqmJXLTMv5mrQAWVde4SnI96ZU8D59
"""

# Student Information Formatter

name = input("Enter student name: ")
branch = input("Enter branch: ")
cgpa = float(input("Enter CGPA: "))

print("\n--- Student Report ---")

print(f"Name   : {name}")
print(f"Branch : {branch}")
print(f"CGPA   : {cgpa}")